# Generated by Django 3.2.3 on 2025-01-09 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Минимальное время приготовление - 1 минута.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (минуты)'),
        ),
    ]
